name: weather_test
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2
  stacked: ^2.2.7
  google_fonts: ^2.1.0
  stacked_services: ^0.8.15
  logger: ^1.1.0
  shared_preferences: ^2.0.9
  # connectivity_plus: ^2.0.3
  dio: ^4.0.3
  # timezone: ^0.8.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner:
  stacked_generator:

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #